### ISSUE TITLE
Give Warren Push access

### ISSUE THREAD

**Issue by wmorning** [japlatt/Physics301#8]
Not sure why, but I can't seem to be able to push to the repository.

I get a permission denied error, so Presumably you just have to give me access to the repo.

**Comment by wmorning** [comment]
https://help.github.com/articles/inviting-collaborators-to-a-personal-repository/

**Comment by japlatt** [comment]
Ok I think I made you a collaborator

**Comment by wmorning** [comment]
Yep.  I am now able to push.
